# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'details.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_details(object):
    def setupUi(self, details):
        details.setObjectName("details")
        details.resize(479, 338)
        details.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("info.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        details.setWindowIcon(icon)
        details.setStyleSheet("*{\n"
"    background-color: rgb(238, 237, 222);\n"
"}")
        self.label = QtWidgets.QLabel(details)
        self.label.setGeometry(QtCore.QRect(0, 0, 481, 341))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(1)
        self.label.setFont(font)
        self.label.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label.setStyleSheet("*{\n"
"    background-color: rgb(231, 236, 252);\n"
"    color:rgb(20, 30, 39);\n"
"    text-align:center;\n"
"    font-size: 20px;\n"
"    padding:10px;\n"
"    \n"
"}")
        self.label.setObjectName("label")

        self.retranslateUi(details)
        QtCore.QMetaObject.connectSlotsByName(details)

    def retranslateUi(self, details):
        _translate = QtCore.QCoreApplication.translate
        details.setWindowTitle(_translate("details", "details"))
        self.label.setText(_translate("details", "    réalisé par:\n"
"\n"
"         • ZAINAB EL MANCHARI\n"
"         • MARIAM EL HASKOURI\n"
"         • ISRAE YAAYA\n"
"         • MOHAMED AINOUZ\n"
"         • YOUSSEF KANJAA\n"
"         • NIZAR AMRI\n"
"\n"
"    Encadrement :\n"
"         • FADIL CHABBABI\n"
"\n"
""))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    details = QtWidgets.QDialog()
    ui = Ui_details()
    ui.setupUi(details)
    details.show()
    sys.exit(app.exec_())
